Enhancement / fake ancient
CodyEngel/fakek pull request #32
Opened 2020-10-06 14:02 UTC by Caps-Looking

Closes #11 

## Description
Creation of a wrapper of fake ancients.

## Technical Details
- Changed `FakeContext` to add `fakeAncient`.
- Added `FakeAncient` class to provide the `fakeAncient`.
- Changed `FakerTypeAliases` to add `FakerAncient` alias.
- Changed `FakerContextTest` to add `fakeAncient` test.
- Added `FakeAncientTest` to test `FakeAncient`.

## Code Samples
```kotlin
fun main() {
    val fakeAncient: FakeAncient(god="God", primordial="Primordial", titan="Titan", hero="Hero")
    fakek { println("Ancient: God - ${fakeAncient.god}, Primordial - ${fakeAncient.primordial}, Titan - ${fakeAncient.titan}, Hero - ${fakeAncient.hero}") }
}
```

Reviewers: @CodyEngel

2020-10-06 15:13 UTC, CodyEngel requested changes
Documentation appears to have a copy/paste error but otherwise changes look good, thank @Caps-Looking.

2020-10-06 15:13 UTC, CodyEngel commented on src/main/kotlin/dev/fakek/fakes/FakeAncient.kt
> + * FakeName provides a fake ancient which includes a god, primordial, titan, and hero.
Should this be `FakeAncient`?

2020-10-06 15:13 UTC, CodyEngel commented on src/main/kotlin/dev/fakek/FakeContext.kt
> +    val fakeAncient by lazy { FakeAncient(fakerAncient) }
Thanks for keeping this in alphabetical order 🙌

2020-10-06 15:41 UTC, Caps-Looking commented on src/main/kotlin/dev/fakek/fakes/FakeAncient.kt
> + * FakeName provides a fake ancient which includes a god, primordial, titan, and hero.
Oops, sorry 😅

2020-10-07 17:15 UTC, CodyEngel approved these changes
LGTM 👍

2020-10-07 17:16 UTC, merged